### ISSUE TITLE
style incompatibility - gmail

### ISSUE THREAD

**Issue by cenglund** [mailchimp/email-blueprints#1]
If you want your email to render better in gmail, you should not use < style >.  Nor should you include anything important in the body tag, in terms of styling.  (I don't mean within the body close body tags.)  

So you should parse these templates into two parts, the css and then the html file.  Then, head to Emogrifier.  You put in each part (the HTML part and the CSS part) and they concatenate it into an HTML template that works in those email clients that tend to strip out style data.

http://www.pelagodesign.com/sidecar/emogrifier/

**Comment by fcarneiro** [comment]
These email blueprints were created primarily for use in MailChimp, where users don't need to inline the CSS before they send - the system automatically inlines the CSS before the campaign is sent.

For uses outside of MailChimp, a user can push the template code through MailChimp Labs' CSS Inliner Tool: http://beaker.mailchimp.com/inline-css Thus, there's no need to break the files up into two parts.
