### ISSUE TITLE
Squirrelmail and responsive templates

### ISSUE THREAD

**Issue by sporkman** [mailchimp/email-blueprints#22]
I guess first question is, are you attempting to support squirrelmail?

If so, it seems to mostly work, but minus backgrounds and some text styling.

While it's a minor market compared to hotmail or AOL, it is still widely bundled with many hosting "control panel" setups.

**Comment by fcarneiro** [comment]
We don't explicitly support SquirrelMail, no. Any issues that present in that client are likely caused by however it deals with HTML email, since the styling included in these emails are as basic as you can get.
