### ISSUE TITLE
Cellpadding ignored with transactional_tabular.html and Outlook 2007-2010

### ISSUE THREAD

**Issue by pierregaste** [mailchimp/email-blueprints#29]
Hi,

We have an issue when we use the `transactional_tabular.html` template with Outlook (2007 and 2010). After the cell concerning "the tabular part", cellpadding concerning the _last message_ and the _button_ cells are ignored.

You can see this problem in my screenshot. I simply sent this template without editing it : 
https://github.com/mailchimp/email-blueprints/blob/master/templates/transactional_tabular.html

Did anyone have a workaround ? I tried to search one, but I really don't understand why this bug occur.
Thanks!

![img_26112014_153234](https://cloud.githubusercontent.com/assets/530648/5203045/73e3ce14-7583-11e4-93ad-b060bd459731.png)

**Comment by bago** [comment]
I confirm this on Outlook 2013 (sending the email via putsmail)

**Comment by bago** [comment]
Here is the simplest html hitting the outlook bug:

``` html
<html>
<body>
  <style type="text/css">
     body { padding:0; }
  </style>
  <table border="1" cellpadding="20">
    <tr>
      <td>
        <table></table>
      </td>
    </tr>
    <tr>
      <td>b</td>
    </tr>
  </table>
</body>
</html>
```

You can put border="0" and the bug will show anyway (I left it to better show the bug).

Note that if I remove the nested table it works, if I switch the 2 <tr> it works.
If I add an id to the body and change the body rule to #selector rule it works.
If I inline "padding: 0" to the body it works.

Another weird outlook bug.... a microsoft guy will sleep harder tonight...

Back to the transaction_tabular, if you simply remove that "padding: 0" in the body rule it will work. Don't ask me why.

**Comment by pierregaste** [comment]
Thanks for you answer @bago ! :smiley: 
It's works but, unfortunately, it's breaking other Webmail which use and correctly apply the padding CSS rules :disappointed:

**Comment by bago** [comment]
what are the broken webmails?
have you tried the proposed workaround? (adding an id to body and put the padding in a #id rule, or adding the padding: 0 inline in the <body style="">) ?

**Comment by pierregaste** [comment]
Yes, this workaround seems to work! :smiley: Thanks you!
The problematic webmail has an other problem with a `*` selector with `padding:0;` and `margin:0;`.

ID selector on the body tag works like a charm!
