### ISSUE TITLE
Extra 1px Table Cell padding in Outlook 2007

### ISSUE THREAD

**Issue by Misplon** [mailchimp/email-blueprints#3]
If you use for example simple-basic.html and send a test to Outlook 2007 without editing the template at all you will get a 1px padded white space around the header image that you don't get in Gmail or a modern web browser. 

This seems to fix the problem: table td {border-collapse: collapse;}  

Reference article: http://www.ianhoar.com/2008/04/29/outlook-2007-borders-and-1px-padding-on-table-cells/

**Comment by fcarneiro** [comment]
This was resolved in the newest update.
