### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by bloggerpact** [mailchimp/email-blueprints#38]
Fatal error: Call to a member function toHtml() on a non-object in /srv/users/serverpilot/apps/magento/public/app/design/adminhtml/default/default/template/mzax/emarketing/filter/test/single.phtml on line 34
![delete it](https://cloud.githubusercontent.com/assets/22036537/20808428/93858aac-b828-11e6-91ee-bed8e8d8c39f.PNG)

**Comment by nicolasdanelon** [comment]
HTML doesn't call functions... WTF ?? r u sure this error is for this repo??

**Comment by bloggerpact** [comment]
If I know wtf it is why would I post here? yes I m sure this error is for this repo you can see file path and line very clearly

**Comment by nicolasdanelon** [comment]
sorry but I dont see phtml flies in thie repo.. are you running magento, right?

**Comment by bloggerpact** [comment]
yes, i m running Magento ver. 1.9.2.4.  I was checking up and found this error. guys, i must say the plugin is awesome best part is open-source love from India. keep doing it.

**Comment by nicolasdanelon** [comment]
![screenshot from 2016-12-01 17-10-23](https://cloud.githubusercontent.com/assets/2846046/20810606/15eaed2e-b7e9-11e6-8700-720873d85a6c.png)
