### ISSUE TITLE
Template in Gmail

### ISSUE THREAD

**Issue by PhilGo20** [mailchimp/email-blueprints#4]
Trying to use you guys templates (simple-letter-head-rightlogo.html) for one of our project. The html found on github renders perfectly in Chrome but when I receive the email in Gmail, most of the CSS is gone.

That seems very unlikely that you guys do not test Gmail, so I am probably missing out on something. Any idea?

**Comment by fcarneiro** [comment]
Phil,

GMail, by default, strips all of the CSS in an email. It's just a problem with the client. A good rule of thumb when working with HTML emails is to always inline your CSS. 

Inlining CSS by hand takes a long time and is more work than you actually need to do, so what you can do before sending is input your HTML into an automatic css inliner.

MailChimp has one here: http://beaker.mailchimp.com/inline-css
Another option is Dialect's Premailer: http://premailer.dialect.ca/

When you've finished your code, drop it in either of those converters and they'll inline for you.

**Comment by PhilGo20** [comment]
Dude, you're too much thanks a lot. was just about to do it manually. 

Thanks!

**Comment by dedril** [comment]
You guys are awesome, love how easy you make it. But can you update the templates so that newbies dont have to hunt down this solution?  Thanks!

**Comment by divyeshdhokiya** [comment]
Thank you @fcarneiro
